name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
env:
  DAY_OF_WEEK: Sunday
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    evnvironment: dev
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "variable one is ${{ vars.VARIABLE1 }}"
      - run: echo "Show day of week ${{ env.DAY_OF_WEEK }}"

      - name: Show Variables
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
          ALLMYINPUTS: ${{ toJSON(inputs) }}
          ALLMYRUNNERS: ${{ toJSON(runner) }}
          ALLMYGITHUBS: ${{ toJSON(github) }}
          ALLMYJOBS: ${{ toJSON(job) }}
          ALLMYENVS: ${{ toJSON(ENV.env) }}
        run: |
          echo  "ALLMYSECRETS"
           echo "$ALLMYSECRETS"
           echo "ALLMYVARS"
           echo "$ALLMYVARS"
           echo "ALLMYINPUTS"
           echo "$ALLMYINPUTS"
           echo "ALLMYRUNNERS"
           echo "$ALLMYRUNNERS"
           echo "ALLMYGITHUBS"
           echo "$ALLMYGITHUBS"
           echo "ALLMYJOBS"
           echo "$ALLMYJOBS"
           echo "ALLMYENVS"
           echo "$ALLMYENVS"
        shell: bash
