name: Run commands
run-name: test for ${{ github.ref_name }} (${{ github.ref_type }}) by @${{ github.actor }}
# comment, context https://docs.github.com/ru/actions/learn-github-actions/contexts

on:
  push:
    branches:
      - workflow-training

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Show files
        run: |
          ls ${{ github.workspace }}

      - name: Show folder
        run: |
          pwd

      - name: Checkout
        uses: actions/checkout@v4

      - name: Show files
        run: |
          ls ${{ github.workspace }}
# separate machine
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: Show files
        run: |
          ls ${{ github.workspace }}