name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show some variable
        run: echo "The operating system on the runner is $env:RUNNER_OS."

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy environment file
        run: cp .env.example .env

      - name: Execute static tests
        run: vendor/bin/phpcs -p --colors

      - name: Execute unit tests
        run: vendor/bin/codecept run Unit
